dist: xenial
os: linux
language: node_js
node_js:
  - "13"

services:
  - docker

before_install:
  - docker build -t bkerbil/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "Running tests against node $(node -v) and npm $(npm -v) ..."
  - docker run bkerbil/react-test npm run test -- --coverage

after_success:
  - docker build -t bkerbil/multi-client ./client
  - docker build -t bkerbil/multi-nginx ./nginx
  - docker build -t bkerbil/multi-server ./server
  - docker build -t bkerbil/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push bkerbil/multi-client
  - docker push bkerbil/multi-nginx
  - docker push bkerbil/multi-server
  - docker push bkerbil/multi-worker
  - echo "All work done!"

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-956601236526"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


